name: CI/CD Pipeline

on:
  push:
    branches: [ main ] # Trigger on pushes to the main branch
  pull_request:
    branches: [ main ] # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - uses: actions/checkout@v3 # Checkout the repository

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Run tests
        run: python -m unittest test_app.py

      - name: Build package
        run: python setup.py sdist bdist_wheel

      - name: Upload artifact (optional, but good practice)
        uses: actions/upload-artifact@v3
        with:
          name: dist # Name of the artifact
          path: dist/* # Path to the built package
